#!/bin/bash
# Generate BuildInfo.swift with git SHA and build date.
# Called by Xcode Run Script build phase (pre-compile).
set -euo pipefail

SRCROOT="${SRCROOT:-$(cd "$(dirname "$0")/.." && pwd)}"
OUT="${SRCROOT}/Sources/BuildInfo.swift"

SHA=$(git -C "$SRCROOT" rev-parse --short=9 HEAD 2>/dev/null || echo "unknown")
DATE=$(date +%Y-%m-%dT%H:%M:%S 2>/dev/null || echo "unknown")

cat > "$OUT" << EOF
// Auto-generated by build script. DO NOT EDIT.
enum BuildInfo {
    static let gitSHA = "$SHA"
    static let buildDate = "$DATE"
}
EOF
